
version: '3.8'

volumes:
  dados_compartilhados:

services:
  data-generator:
    image: data-generator
    volumes:
      - dados_compartilhados:/app/data
    working_dir: /app
    entrypoint: ""

  local-processing:
    image: local-processing
    volumes:
      - dados_compartilhados:/app/data
    working_dir: /app
    entrypoint: ""

  spark-processing:
    image: spark-processing
    volumes:
      - dados_compartilhados:/app/data
    working_dir: /app
    environment:
      - SPARK_PARALLELISM=4 
    entrypoint: ""

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  message-broker:
    image: message-broker
    depends_on:
      - rabbitmq
    volumes:
      - dados_compartilhados:/app/data
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    working_dir: /app
    entrypoint: ""
    command: celery -A tasks worker --loglevel=info --concurrency=${CELERY_CONCURRENCY:-1}
