
version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  data-generator:
    build:
      context: .
      dockerfile: data-generator/Dockerfile
    volumes:
      - ./data:/app/data
    container_name: data-generator

  local-processing:
    build:
      context: .
      dockerfile: approach_a_local/Dockerfile
    volumes:
      - ./data:/app/data
    container_name: local-processing

  message-broker:
    build:
      context: .
      dockerfile: approach_b_message_broker/Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - rabbitmq
    container_name: message-broker

  spark-processing:
    build:
      context: .
      dockerfile: approach_c_spark/Dockerfile
    volumes:
      - ./data:/app/data
      - ./output:/app/output
    container_name: spark-processing

